"""Core package for NARVIS."""

from .capabilities import (
    RuntimeCapabilityManifest,
    RuntimeCapabilityManifestService,
    RuntimeCapabilitySource,
    RuntimeCapabilitySummary,
    RuntimeExecutionMode,
    RuntimeProviderMode,
    RuntimeReadinessCalculator,
    RuntimeReadinessContext,
    RuntimeReadinessLevel,
    RuntimeReadinessReport,
)
from .diagnostics import (
    RUNTIME_DIAGNOSTICS_STARTED_EVENT,
    RUNTIME_DIAGNOSTICS_STOPPED_EVENT,
    RuntimeBuildMetadata,
    RuntimeCompatibilityMetadata,
    RuntimeCompatibilityStatus,
    RuntimeDiagnostics,
    RuntimeDiagnosticsEvents,
    RuntimeDiagnosticsLifecycleAdapter,
    RuntimeDiagnosticsSnapshot,
    RuntimeDiagnosticsSummary,
    RuntimeHealthCalculator,
    RuntimeHealthContext,
    RuntimeHealthReport,
    RuntimeHealthStatus,
    RuntimeLifecycleMetadata,
    RuntimeLifecycleState,
)
from .optimization import (
    OptimizationSnapshot,
    RuntimeMetric,
    RuntimeOptimizationService,
    register_runtime_optimization_services,
)
from .plugins import (
    ManagedPluginHook,
    PluginDescriptor,
    PluginRegistry,
    RegisteredPlugin,
    register_plugin_services,
)
from .service_registry import (
    RuntimeCompatibilitySummary,
    RuntimeDependencyGraphSummary,
    RuntimeDependencyHealthReport,
    RuntimeServiceDependency,
    RuntimeServiceRecord,
    RuntimeServiceRegistry,
    RuntimeServiceRegistrySnapshot,
)
from .system import ServiceRegistrationMetadata

__all__ = [
    "ManagedPluginHook",
    "OptimizationSnapshot",
    "PluginDescriptor",
    "PluginRegistry",
    "RegisteredPlugin",
    "RuntimeMetric",
    "RuntimeOptimizationService",
    "RUNTIME_DIAGNOSTICS_STARTED_EVENT",
    "RUNTIME_DIAGNOSTICS_STOPPED_EVENT",
    "RuntimeBuildMetadata",
    "RuntimeCapabilityManifest",
    "RuntimeCapabilityManifestService",
    "RuntimeCapabilitySource",
    "RuntimeCapabilitySummary",
    "RuntimeCompatibilityMetadata",
    "RuntimeCompatibilityStatus",
    "RuntimeCompatibilitySummary",
    "RuntimeDependencyGraphSummary",
    "RuntimeDependencyHealthReport",
    "RuntimeDiagnostics",
    "RuntimeDiagnosticsEvents",
    "RuntimeDiagnosticsLifecycleAdapter",
    "RuntimeDiagnosticsSnapshot",
    "RuntimeDiagnosticsSummary",
    "RuntimeExecutionMode",
    "RuntimeHealthCalculator",
    "RuntimeHealthContext",
    "RuntimeHealthReport",
    "RuntimeHealthStatus",
    "RuntimeLifecycleMetadata",
    "RuntimeLifecycleState",
    "RuntimeProviderMode",
    "RuntimeReadinessCalculator",
    "RuntimeReadinessContext",
    "RuntimeReadinessLevel",
    "RuntimeReadinessReport",
    "RuntimeServiceDependency",
    "RuntimeServiceRecord",
    "RuntimeServiceRegistry",
    "RuntimeServiceRegistrySnapshot",
    "ServiceRegistrationMetadata",
    "register_plugin_services",
    "register_runtime_optimization_services",
]
