"""Public lifecycle API for the UI-independent Conversation layer."""

from .archive import (
    ArchiveRepository,
    ArchiveService,
    ConversationArchiveService,
    InMemoryArchiveRepository,
    InMemoryArchiveStore,
)
from .cleanup import CleanupService, ConversationCleanupService
from .events import (
    CONVERSATION_ARCHIVED_EVENT,
    CONVERSATION_CLEANED_EVENT,
    CONVERSATION_EXPIRED_EVENT,
    CONVERSATION_RESTORED_EVENT,
    CONVERSATION_SESSION_SWITCHED_EVENT,
    ConversationLifecycleEvents,
)
from .exceptions import (
    CleanupError,
    ConversationAlreadyArchivedError,
    ConversationArchiveError,
    ConversationExpiredError,
    ConversationExportError,
    ConversationLifecycleError,
    ConversationNotArchivedError,
    LifecycleValidationError,
    NoCurrentSessionError,
    RetentionPolicyError,
    SessionRemovalUnsupportedError,
    SessionSwitchError,
)
from .export import ConversationExportBuilder, ConversationExporter, ExportBuilder
from .manager import ConversationLifecycleManager, LifecycleManager
from .models import (
    ArchiveMetadata,
    CleanupCandidate,
    CleanupReason,
    CleanupReport,
    ContextCleanupPolicy,
    ConversationExport,
    ConversationHealth,
    ExportFormat,
    HealthStatus,
    RetentionPolicy,
    SessionInfo,
    SessionSwitch,
)

__all__ = [
    "ArchiveMetadata",
    "ArchiveRepository",
    "ArchiveService",
    "CONVERSATION_ARCHIVED_EVENT",
    "CONVERSATION_CLEANED_EVENT",
    "CONVERSATION_EXPIRED_EVENT",
    "CONVERSATION_RESTORED_EVENT",
    "CONVERSATION_SESSION_SWITCHED_EVENT",
    "CleanupCandidate",
    "CleanupError",
    "CleanupReason",
    "CleanupReport",
    "CleanupService",
    "ContextCleanupPolicy",
    "ConversationAlreadyArchivedError",
    "ConversationArchiveError",
    "ConversationArchiveService",
    "ConversationCleanupService",
    "ConversationExpiredError",
    "ConversationExport",
    "ConversationExportBuilder",
    "ConversationExportError",
    "ConversationExporter",
    "ConversationHealth",
    "ConversationLifecycleError",
    "ConversationLifecycleEvents",
    "ConversationLifecycleManager",
    "ConversationNotArchivedError",
    "ExportBuilder",
    "ExportFormat",
    "HealthStatus",
    "InMemoryArchiveRepository",
    "InMemoryArchiveStore",
    "LifecycleManager",
    "LifecycleValidationError",
    "NoCurrentSessionError",
    "RetentionPolicy",
    "RetentionPolicyError",
    "SessionInfo",
    "SessionRemovalUnsupportedError",
    "SessionSwitch",
    "SessionSwitchError",
]
