"""Phase 10 Computer Integration Layer foundation for NARVIS."""

from .exceptions import (
    ApplicationServiceError,
    ClipboardServiceError,
    ComputerCapabilityDiscoveryError,
    ComputerInformationServiceError,
    ComputerProviderAlreadyInitializedError,
    ComputerProviderHealthError,
    ComputerProviderInitializationError,
    ComputerProviderInspectionError,
    ComputerProviderLifecycleError,
    ComputerProviderNotFoundError,
    ComputerProviderNotInitializedError,
    ComputerProviderShutdownError,
    ComputerRegistryError,
    ComputerServiceError,
    DuplicateComputerProviderError,
    DuplicateProviderError,
    FileSystemServiceError,
    ProcessServiceError,
    ProviderAlreadyRegisteredError,
    ProviderNotFoundError,
    ProviderNotRegisteredError,
)
from .interfaces import EventPublisher
from .manager import ComputerManager
from .models import (
    ApplicationInfo,
    ApplicationMetadata,
    ClipboardMetadata,
    ComputerCapability,
    ComputerHealth,
    ComputerProviderInfo,
    ComputerStatus,
    FileMetadata,
    FileSystemEntry,
    FileSystemEntryKind,
    ProcessInfo,
    ProcessMetadata,
)
from .provider import ComputerProvider
from .registry import ComputerRegistry

__all__ = [
    "ApplicationInfo",
    "ApplicationMetadata",
    "ApplicationServiceError",
    "ClipboardMetadata",
    "ClipboardServiceError",
    "ComputerCapability",
    "ComputerCapabilityDiscoveryError",
    "ComputerHealth",
    "ComputerInformationServiceError",
    "ComputerManager",
    "ComputerProvider",
    "ComputerProviderAlreadyInitializedError",
    "ComputerProviderHealthError",
    "ComputerProviderInfo",
    "ComputerProviderInitializationError",
    "ComputerProviderInspectionError",
    "ComputerProviderLifecycleError",
    "ComputerProviderNotFoundError",
    "ComputerProviderNotInitializedError",
    "ComputerProviderShutdownError",
    "ComputerRegistry",
    "ComputerRegistryError",
    "ComputerServiceError",
    "ComputerStatus",
    "DuplicateComputerProviderError",
    "DuplicateProviderError",
    "EventPublisher",
    "FileMetadata",
    "FileSystemEntry",
    "FileSystemEntryKind",
    "FileSystemServiceError",
    "ProcessInfo",
    "ProcessMetadata",
    "ProcessServiceError",
    "ProviderAlreadyRegisteredError",
    "ProviderNotFoundError",
    "ProviderNotRegisteredError",
]
