"""AI package for NARVIS."""

from .brain import BrainEngine
from .conversation import ChatHistoryManager, ConversationManager, SessionManager
from .context import ConversationContext, InMemoryContextManager
from .core import (
    AIManager,
    AIOrchestratorError,
    AIOrchestratorManager,
    AIProvider,
    AIProviderRegistry,
    AIRequest,
    AIResponse,
    AIValidationError,
    AI_PROVIDER_REGISTERED_EVENT,
    AI_PROVIDER_REMOVED_EVENT,
    AI_PROVIDER_SELECTED_EVENT,
    DefaultProviderSelector,
    NoEligibleProviderError,
    PriorityProviderSelector,
    ProviderAlreadyRegisteredError,
    ProviderCapability,
    ProviderCapabilityError,
    ProviderCatalog,
    ProviderDescriptor,
    ProviderHealth,
    ProviderHealthError,
    ProviderManager,
    ProviderMetadata,
    ProviderNotFoundError,
    ProviderPriority,
    ProviderRegistry,
    ProviderRegistryError,
    ProviderSelectionStrategy,
    ProviderSnapshotFactory,
    ProviderStatus,
    ProviderUnavailableError,
)
from .intent import (
    IntentAnalyzer,
    IntentClassification,
    IntentType,
    RuleBasedIntentClassifier,
)
from .prompts import PromptBuilder
from .providers import (
    ClaudeProvider,
    GeminiProvider,
    OllamaProvider,
    OpenAIProvider,
    Provider,
    ProviderFactory,
)
from .response import BrainResponse, ResponseBuilder
from .router import IntentRouter, ModuleRoute

__all__ = [
    "AIManager",
    "AIOrchestratorError",
    "AIOrchestratorManager",
    "AIProvider",
    "AIProviderRegistry",
    "AIRequest",
    "AIResponse",
    "AIValidationError",
    "AI_PROVIDER_REGISTERED_EVENT",
    "AI_PROVIDER_REMOVED_EVENT",
    "AI_PROVIDER_SELECTED_EVENT",
    "BrainEngine",
    "BrainResponse",
    "ChatHistoryManager",
    "ClaudeProvider",
    "ConversationContext",
    "ConversationManager",
    "DefaultProviderSelector",
    "GeminiProvider",
    "InMemoryContextManager",
    "IntentAnalyzer",
    "IntentClassification",
    "IntentRouter",
    "IntentType",
    "ModuleRoute",
    "NoEligibleProviderError",
    "OllamaProvider",
    "OpenAIProvider",
    "PromptBuilder",
    "Provider",
    "ProviderAlreadyRegisteredError",
    "ProviderCapability",
    "ProviderCapabilityError",
    "ProviderCatalog",
    "ProviderDescriptor",
    "ProviderFactory",
    "ProviderHealth",
    "ProviderHealthError",
    "ProviderManager",
    "ProviderMetadata",
    "ProviderNotFoundError",
    "ProviderPriority",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderSelectionStrategy",
    "ProviderSnapshotFactory",
    "ProviderStatus",
    "ProviderUnavailableError",
    "PriorityProviderSelector",
    "ResponseBuilder",
    "RuleBasedIntentClassifier",
    "SessionManager",
]
