"""Voice package exports for the NARVIS runtime."""

from .audio import AudioDeviceInfo, AudioFormat, AudioFrame, AudioSink
from .engines import (
    GoogleSpeechRecognitionEngine,
    OfflineSpeechRecognitionEngine,
    Pyttsx3TextToSpeechEngine,
    RealSpeechToTextEngine,
    RealTextToSpeechEngine,
)
from .listener import Listener, VoiceListener
from .manager import (
    VoiceCommandProcessor,
    VoiceManager,
    VoiceQueue,
    VoiceSession,
    VoiceSessionManager,
    VoiceState,
    VoiceSystemManager,
)
from .microphone import AudioCaptureSession, AudioInputService, BaseMicrophone, Microphone, MicrophoneService, NullMicrophone
from .realmic import RealMicrophone, VoiceActivityDetector
from .speaker import Speaker, SpeakerService, VoiceSpeaker
from .speech import (
    BaseSpeechToTextEngine,
    BaseTextToSpeechEngine,
    NullSpeechToTextEngine,
    NullTextToSpeechEngine,
    PassthroughSpeechToText,
    PassthroughTextToSpeech,
    SpeechRecognitionService,
    SpeechToTextEngine,
    TextToSpeechEngine,
)
from .voice import (
    VoiceConfiguration,
    VoiceRuntimeHook,
    VoiceRuntimeService,
    VoiceServices,
    build_voice_services,
    register_voice_services,
)
from .wakeword import (
    BaseWakeWordDetector,
    KeywordWakeWordDetector,
    NullWakeWordDetector,
    PorcupineWakeWordDetector,
    WakeWordDetector,
    WakeWordEvent,
    WakeWordService,
)

__all__ = [
    "AudioCaptureSession",
    "AudioDeviceInfo",
    "AudioFormat",
    "AudioFrame",
    "AudioInputService",
    "AudioSink",
    "BaseMicrophone",
    "BaseSpeechToTextEngine",
    "BaseTextToSpeechEngine",
    "BaseWakeWordDetector",
    "GoogleSpeechRecognitionEngine",
    "KeywordWakeWordDetector",
    "Listener",
    "Microphone",
    "MicrophoneService",
    "NullMicrophone",
    "NullSpeechToTextEngine",
    "NullTextToSpeechEngine",
    "NullWakeWordDetector",
    "OfflineSpeechRecognitionEngine",
    "PassthroughSpeechToText",
    "PassthroughTextToSpeech",
    "PorcupineWakeWordDetector",
    "Pyttsx3TextToSpeechEngine",
    "RealMicrophone",
    "RealSpeechToTextEngine",
    "RealTextToSpeechEngine",
    "Speaker",
    "SpeakerService",
    "SpeechRecognitionService",
    "SpeechToTextEngine",
    "TextToSpeechEngine",
    "VoiceActivityDetector",
    "VoiceCommandProcessor",
    "VoiceConfiguration",
    "VoiceListener",
    "VoiceManager",
    "VoiceQueue",
    "VoiceRuntimeHook",
    "VoiceRuntimeService",
    "VoiceServices",
    "VoiceSession",
    "VoiceSessionManager",
    "VoiceSpeaker",
    "VoiceState",
    "VoiceSystemManager",
    "WakeWordDetector",
    "WakeWordEvent",
    "WakeWordService",
    "build_voice_services",
    "register_voice_services",
]
