"""Observe-only self-evolution foundations for NARVIS."""

from .inventory import CapabilityInventoryBuilder
from .models import (
    ApprovalDecision,
    CapabilityGap,
    CapabilityInventorySnapshot,
    CapabilityRecord,
    ChangePlan,
    ChangeJournalEntry,
    ChangeProposal,
    DiscoveryCandidate,
    DiscoveryQueryResult,
    ExecutionAuthorization,
    ExecutionRequest,
    ExecutionStepRequest,
    EvaluationRecord,
    EvidenceRecord,
    EvolutionAutonomyLevel,
    LearnedOutcome,
    PlanStep,
    RecoveryObservation,
    RecoveryOutcome,
    RecoveryRequirement,
    RecoveryRun,
    RecoveryStepRun,
    VerificationObservation,
    VerificationOutcome,
    VerificationRequirement,
    VerificationRun,
    VerificationStepRun,
)
from .runtime import EvolutionPolicy, SelfEvolutionService, build_evolution_service, register_evolution_services

__all__ = [
    "ApprovalDecision",
    "CapabilityGap",
    "CapabilityInventorySnapshot",
    "CapabilityInventoryBuilder",
    "CapabilityRecord",
    "ChangePlan",
    "ChangeJournalEntry",
    "ChangeProposal",
    "DiscoveryCandidate",
    "DiscoveryQueryResult",
    "ExecutionAuthorization",
    "ExecutionRequest",
    "ExecutionStepRequest",
    "EvaluationRecord",
    "EvidenceRecord",
    "EvolutionAutonomyLevel",
    "EvolutionPolicy",
    "LearnedOutcome",
    "PlanStep",
    "RecoveryObservation",
    "RecoveryOutcome",
    "RecoveryRequirement",
    "RecoveryRun",
    "RecoveryStepRun",
    "SelfEvolutionService",
    "VerificationObservation",
    "VerificationOutcome",
    "VerificationRequirement",
    "VerificationRun",
    "VerificationStepRun",
    "build_evolution_service",
    "register_evolution_services",
]
